//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknik_Servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEPET
    {
        public int ID { get; set; }
        public string VERGINO { get; set; }
        public string ADSOYAD { get; set; }
        public string TELEFON { get; set; }
        public string BARKODNO { get; set; }
        public string AD { get; set; }
        public Nullable<int> MIKTAR { get; set; }
        public Nullable<decimal> SATISFİYAT { get; set; }
        public Nullable<decimal> TOPLAMFIYAT { get; set; }
        public string TARIH { get; set; }
    }
}
