//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknik_Servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBAKIYE
    {
        public byte ID { get; set; }
        public Nullable<byte> PERSONEL { get; set; }
        public string BAKIYE { get; set; }
        public string TARIH { get; set; }
    
        public virtual TBLPERSONEL TBLPERSONEL { get; set; }
    }
}
